postCreateUser:
  handler: controllers/create.postUser
  memorySize: 128
  description: Create new user
  events:
    - http:
        path: users
        method: post
getListUsers:
  handler: controllers/read.getUsers
  memorySize: 128
  description: List all users
  events:
    - http:
        path: users
        method: get
sampleQueueHandler:
  handler: controllers/sqs.readUser
  events:
    - sqs:
        arn:
          Fn::GetAtt:
            - ApiSampleQueue
            - Arn